### ISSUE TITLE
Incompatibility between Python 3.10 and `collections.Mapping`

### ISSUE THREAD

**Issue by NeptuneProjects** [aimhubio/aimlflow#16]
Running `aimlflow sync` with Python 3.10+ environment produces the following error:

```python
Traceback (most recent call last):
  File "~/mambaforge-pypy3/envs/gp310/bin/aimlflow", line 8, in <module>
    sys.exit(cli_entry_point())
  File "~/mambaforge-pypy3/envs/gp310/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "~/mambaforge-pypy3/envs/gp310/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "~/mambaforge-pypy3/envs/gp310/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "~/mambaforge-pypy3/envs/gp310/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/mambaforge-pypy3/envs/gp310/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "~/mambaforge-pypy3/envs/gp310/lib/python3.10/site-packages/aimlflow/cli.py", line 41, in sync
    convert_existing_logs(repo_inst, mlflow_tracking_uri, experiment, exclude_artifacts)
  File "~/mambaforge-pypy3/envs/gp310/lib/python3.10/site-packages/aimlflow/utils.py", line 228, in convert_existing_logs
    collect_run_params(aim_run, run)
  File "~/mambaforge-pypy3/envs/gp310/lib/python3.10/site-packages/aimlflow/utils.py", line 115, in collect_run_params
    aim_run['params'] = _map_nested_dicts(_try_parse_str, mlflow_run.data.params)
  File "~/mambaforge-pypy3/envs/gp310/lib/python3.10/site-packages/aimlflow/utils.py", line 248, in _map_nested_dicts
    if isinstance(tree, collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'
```

I verified this by running the same command with a Python 3.9 environment and it worked as expected. My understanding is that `collections.Mapping` was deprecated in Python 3.10 and replaced with `collections.abc.Mapping` ([source](https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes)), but I haven't been able to verify this with `aimlflow` yet.

**Comment by gorarakelyan** [comment]
hey @NeptuneProjects, thanks for reporting! Any chance you would like to contribute? Would be happy to help you in any way I can/

**Comment by NeptuneProjects** [comment]
@gorarakelyan sure thing, just submitted the PR.

**Comment by gorarakelyan** [comment]
@NeptuneProjects just merged the PR. Congrats on the contribution 🎉 We will release a patch version shortly.

**Comment by NeptuneProjects** [comment]
Thanks, glad to be of assistance!
