### ISSUE TITLE
Error: No module named `aim.sdk`

### ISSUE THREAD

**Issue by pourmand1376** [aimhubio/aimlflow#25]
I've installed your package via `pip install aim-mlflow` or `pip install git+https://github.com/aimhubio/aimlflow` and both ways I get this error when running `aimlflow`:
```
/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.1.0) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/emofid.com/a.pourmand/.local/bin/aimlflow", line 5, in <module>
    from aimlflow.cli import cli_entry_point
  File "/home/emofid.com/a.pourmand/.local/lib/python3.10/site-packages/aimlflow/cli.py", line 8, in <module>
    from aim.sdk.repo import Repo
ModuleNotFoundError: No module named 'aim.sdk'
```

Python Version: 3.10

**Comment by fzyzcjy** [comment]
Hi, did you solve the problem? Thanks

**Comment by pourmand1376** [comment]
Nope! I went back using the same old mlflow.

**Comment by fzyzcjy** [comment]
I see, thank you!
